### ISSUE TITLE
The latest version can't load the WDL/cromwell-58.jar correctly

### ISSUE THREAD

**Issue by wangjiaxuan666** [broadinstitute/CTAT-VirusIntegrationFinder#41]
I have installed CTAT-vif, and get some result in my workflow. But recently I find it upgrade !, and I find it become more and more power and comprehensive.
 
So I want to reinstall a new version and add my analysis workflow, but after download the zip, and success make it. but when I run it next, it display  some error message:

```
Error: Invalid or corrupt jarfile ~/wangjiaxuan/biosoft/CTAT-vif/WDL/cromwell-58.jar
```

 And I try to down it from the github use web browser，or let co-worker also download ，even I try to down cromwell-59，those all failed. 😞 

it's very dispirited，and I notice Previous version don't have cromwell in WDL file. how to slove the problem.

thanks

**Comment by wangjiaxuan666** [comment]
full log is
```
Error: Invalid or corrupt jarfile ~/wangjiaxuan/biosoft/CTAT-vif/WDL/cromwell-58.jar
Traceback (most recent call last):
  File "~/wangjiaxuan/biosoft/CTAT-vif/ctat-vif", line 275, in <module>
    main()
  File "~/wangjiaxuan/biosoft/CTAT-vif/ctat-vif", line 255, in main
    with open(meta_file, 'rt', encoding='UTF-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '~/wangjiaxuan/biosoft/CTAT-vif/ctat-vif.meta.json'
```

**Comment by brianjohnhaas** [comment]
Running 'make' in the base directory should pull down the cromwell.jar file
needed.  You can try doing it manually via:

wget
https://github.com/broadinstitute/cromwell/releases/download/58/cromwell-58.jar
-O WDL/cromwell-58.jar

and testing it with

   java -jar cromwell-58.jar






On Sun, Jan 9, 2022 at 2:17 AM Jiaxuan Wang ***@***.***>
wrote:
>
> full log is
>
> Error: Invalid or corrupt jarfile
~/wangjiaxuan/biosoft/CTAT-vif/WDL/cromwell-58.jar
> Traceback (most recent call last):
>   File "~/wangjiaxuan/biosoft/CTAT-vif/ctat-vif", line 275, in <module>
>     main()
>   File "~/wangjiaxuan/biosoft/CTAT-vif/ctat-vif", line 255, in main
>     with open(meta_file, 'rt', encoding='UTF-8') as f:
> FileNotFoundError: [Errno 2] No such file or directory:
'~/wangjiaxuan/biosoft/CTAT-vif/ctat-vif.meta.json'
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you are subscribed to this thread.Message
ID: <broadinstitute/CTAT-VirusIntegrationFinder/issues/41/
***@***.***>



--
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas

**Comment by wangjiaxuan666** [comment]
I find the problem where is error ,my java version is 1.7, not the cromwell required version 1.8+

**Comment by wangjiaxuan666** [comment]
CTAT-vif software is very pretty and very awesome, which worth I study
